### ISSUE TITLE
latest Firefox TLS issues

### ISSUE THREAD

**Issue by DibyaTheXPFan** [MyTDT-Mysoft/DllCompat#11] opened 2018-12-01 16:36 UTC
Do you have any fix ?

**Comment by MyTDT-Mysoft** [comment] 2018-12-01 17:23
if thats about the TLS on dynamic loaded libraries... then thats what tls_deps.dll is for
one would put build a custom (per project) tls_deps.dll along kernel3x and add the libraries that require static linking (at program load) there...

**Comment by pachuco** [comment] 2019-12-31 21:28
Duplicate of #6

**Closed as completed by pachuco** 2019-12-31 21:28 UTC
